# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30d7194b2f1ca37cb58d0d9f2514e0cd14fffe3b1bec3973d3259180477477b0cccb765a3ede77bea6175b21204648a8bcc5b15954b7ddf3ddfad3abeda52ab0

test:
  secret_key_base: 152f1225bfb6f60dbe07f99443d8e870abdaa51a1cdd05007cf12c4371d8ad807ef9efe4387ad8130619e9c98add5ebf68b0412a85e0696e5dae036f4afae9c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
